#+INCLUDE: "~/org/uni/org/config.org"
#+FILETAGS: :university:
#+LATEX_HEADER: \usepackage{venndiagram}



* TOC :TOC_2:noexport:
- [[#clases][Clases]]
  - [[#about][About]]
  - [[#2022-04-01-fri-clase][[2022-04-01 Fri] Clase]]
  - [[#2022-04-05-tue-clase][[2022-04-05 Tue] Clase]]
  - [[#2022-04-08-fri-clase][[2022-04-08 Fri] Clase]]
  - [[#2022-04-12-tue][[2022-04-12 Tue]]]
  - [[#2022-04-26-tue-primera-clase-después-de-la-1-prueba][[2022-04-26 Tue] Primera clase después de la 1 prueba]]
- [[#ayudantías][Ayudantías]]
  - [[#inactive-time-stamp-clase-x][inactive-time-stamp clase x]]
  - [[#2022-04-13-wed-ayudantía-1][[2022-04-13 Wed] Ayudantía 1]]
- [[#resúmenes-para-evaluaciones][Resúmenes para evaluaciones]]

* Clases :lecture:
** About
- Copia el contenido de "Clases" en "asignatura.org"
- Pegalo en esta sección
- Elimina el dia, dejando las clases únicamente
- Selecciona visualmente las clases
  + Tambien puedes seleccionar el contenido del heading "Clases", es lo mismo.
    - Se hace con =v i R=: "visual inside R"
      + La R hace referencia al contenido interior de un heading
- =org-sort= alpha


- Asi deberias tener luego las clases ordenadas por numero de clase
- Mientras que en "asignatura.org" estaran ordenadas por el dia
** [2022-03-15 Tue] Clase :noexport:
:PROPERTIES:
:ID:       36e1b271-8b68-4238-95b0-4350908e5a3f
:END:
- [2022-03-15 Tue 11:33]


- R, Python.
- Ejemplos covid.
- Ingeniería social.


- Promedio vs moda vs mediana.
  - Sesgo en distribuciones.
  - Promedio = media = media aritmética.
- Ejemplo de diferencia de sueldo por género.
  - ¿Ganan más dinero los hombres para un mismo
    trabajo?
  - Caso Enfermería.
  - Caso Párvulos.
  - Distribución Normal para IQ de hombres vs mujeres.
    - IQ de mujeres es tiene más curtosis.
      La distribución de IQ para la curva de hombres
      está más esparcida.
    - Sin embargo, el promedio es el mismo.
  - Curva distribución del ingreso en Chile.
- Prueba de hipótesis.


- Tableau
- PowerBI
- SAS


- Primera prueba: Significado de las cosas.
- Segunda prueba: Probabilidad.
- Tercera prueba: Modelos de regresión.
  - Redes neuronales, AI, Regresion Logística.
  - Ej: Bancos usan Regresiones Logísticas para
    calculo de riesgo para un crédito.

-----
** [2022-03-18 Fri] Clase :noexport:
:PROPERTIES:
:ID:       4109903c-5882-49a7-b531-0b3f59d11352
:END:
:CLOCKBOOK:
CLOCK: [2022-03-18 Fri 08:31]--[2022-03-20 Sun 16:32] => 56:01
:END:

Resumen: Acerca de control de procesos y
la calidad su medición.

-----
- Campus/ Sem 1/CONCEPTUALIZANDO parte 1


- Etapas de la Investigación Estadística.
  - Defina el Problema, Los Objetivos, Las Hipótesis.
  - Defina las Variables de Análisis.
  - Defina la Población de trabajo o muestra.
  - Defina que instrumentos utilizará para
    medir las variables.
  - Defina el procedimiento estadístico para
    analizar los datos.
  - Obtenga Resultados.
  - Responda las Hipótesis.
  - Concluya.

-----
- ¿Cómo reconocemos un PROBLEMA o
  cómo lo encontramos?: Por lo general es una
  pregunta relacionada al desconocimiento de algo.
  - ¿El producto cumple con la norma?
    - Ejemplo botella de pisco de 750cc.
      - ¿Cúanto puede ser el delta? 10cc? El rango
        entonces es 740-760cc?
      - ¿Cómo se puede medir?
    - Ejemplo cajas de fósforo: empresa demandada
      por entregar a veces 38 o a veces 45 fósforos,
      siendo que publicitan 40 en cada caja.
    - El objeto es el /error/ en las muestras.

  - ¿Cómo se comporta la producción?
    - Opciones:
      - Bien/Mal.
      - Defectuoso.
      - Regular.
    - Implícitamente asignamos un número al
      comportamiento.

  - ¿Qué variables explican el comportamiento
    de la variación de un producto?
    - ¿Qué es lo que provoca las pequeñas
      alteraciones o errores en la producción?
    - ¿Quién sostiene esos errores?
      - El consumidor, siempre.

  - ¿Qué explica mejor la variación del producto
    para controlar su fluctuación?
    - El jefe pregunta por esto, no la anterior.

-----
- Componentes de un Problema:
  - Diagrama Ishikawa:
    - aka Causa-Efecto.
    - aka Espina de Pescado.

  - Variable Dependiente (Y). Aquella que se mide
    y donde se centra la respuesta. Por lo general
    la respuesta al problema se asocia con lo que
    le ocurre a esta variable.

  - Contexto. Datos que permiten establecer en
    condiciones se mide Y, además permite entender
    el porque de los resultados de Y.
    - El porqué de los resultados.

  - Acción. Concepto, que permite saber que se
    desea conocer de Y.
    - ¿Qué tipo de análisis voy a ejercer sobre ...?

  - Variable independiente (X), aquella que agrupa
    o explica la variación de Y, no siempre
    se identifica primariamente en un problema
    o puede no estar presente.

-----
- Claves
  - Accion
  - Variables
  - Contexto

  - ¿Cómo se comporta la producción de paneles
    SIP en la región de La Araucanía?

-----
- Campus/ Sem 1/CONCEPTUALIZANDO parte 2


- [[4109903c-5882-49a7-b531-0b3f59d11352-custom1][Variable: Dependencia.]]
- [[4109903c-5882-49a7-b531-0b3f59d11352-custom2][Variable: Tipología.]]
- [[4109903c-5882-49a7-b531-0b3f59d11352-custom3][Variable: Escala.]]


Variables: ¿Cómo se entiende una variable?

Por definición es algo que esta sujeto a
cambios frecuentes.

También debe entenderse como aquella
característica medida en una unidad
experimental (persona, animal, objeto, etc),
que presenta fluctuación intra medidas y
entre medidas.

- Intra medida. El mismo objeto evaluado \(n\) veces.
- Entre medida. \(n\) objetos medidos con el
  mismo instrumento.
  - Ejemplo al pesarse: la misma persona con la
    misma balanza se pesa varias veces seguidas y
    aun así hay diferencias. Factores que afectan
    el error: presión atmosférica, la altitud.
  - Lección: las condiciones de medición deben
    ser las mismas.
  - Ejemplo de pesar sillas americanas: 30
    sillas diferentes van a pesar diferente a
    pesar de ser el mismo modelo y marca:
    simplemente no son iguales, son semejantes,
    pero para efectos prácticos son la misma silla.
  - Premisa: las sillas no son iguales. Si medición
    arroja que /sí/ son iguales: el proceso
    productivo es muy bueno.
  - Acerca de la calidad del dato y los indicadores.
  - Ejemplo de notas: ¿Qué tan representativo
    es el promedio de notas respecto de la
    realidad del curso? Caso: 80 % notas sobre 40,
    pero un par de casos extremos bajan el promedio
    general al 39.

-----

<<4109903c-5882-49a7-b531-0b3f59d11352-custom1>>
Variables: ¿Cómo se clasifican?: Dependencia.

Se entiende como la relación funcional de la
variable, es una variable que explica
(independiente) o que es explicada (dependiente).


¿Diferencia entre objetivo y subjetivo?
- Objetivo: cuando más de una persona opina
  lo mismo sobre un mismo fenómeno.
- Subjetivo: cuando al menos una persona opina
  algo diferente respecto de un mismo fenómeno.

-----

<<4109903c-5882-49a7-b531-0b3f59d11352-custom2>>
Variables: ¿Cómo se clasifican?: Tipología.

Clasificación que dice relación con la forma.
1) Cualitativo:
   1) Nominal.
      - El orden no importa.
   2) Ordinal.
      - El orden sí importa.
2) Cuantitativo
   1) Discreto.
      - Números Enteros.
   2) Continuo.
      - Números Reales.


- La edad es un continuo.


- ¿En qué escenario todas las personas deberían
  tener el mismo sueldo?
-----

<<4109903c-5882-49a7-b531-0b3f59d11352-custom3>>
Variables: ¿Cómo se clasifican?: Escala.

Es una clasificación que tiene por fin,
describir la naturaleza de la información
contenida dentro de los objetos,
a través de números.

-----

Población y Muestra

Población se entenderá en estadística,
como el conjunto total de unidades
experimentales (personas, objetos, animales, etc.),
que están contextualizados por una serie de
características que funcionan como discriminadores.

Ejemplo: ¿Cómo debe ser un celular para ser
considerado bueno? ¿A quién le debo preguntar
la opinión? ¿Quién clasifica como opinión relevante?

** [2022-04-01 Fri] Clase
:CLOCKBOOK:
CLOCK: [2022-04-01 Fri 09:18]--[2022-04-01 Fri 11:00] =>  1:42
:END:
- [2022-04-01 Fri 09:18]


- Leptocurtosis
- Mesocurtosis
- Platocurtosis


- Medidas de forma: Asimetría.
  - Positiva: cola hacia la derecha.
  - Negativa: cola hacia la izquierda.


- Bisagras:
  - \( b_{max}=P_{75} + 1.5 IQR \)
  - \( b_min=P_{25} - 1.5 IQR \)
  - \( IQR=P_{75} - P_{25} \)

** [2022-04-05 Tue] Clase

- Tarea: Dashboard:
  - Generar o realizar uno.
  - Indicadores tipo KPI.
  - Buscar: "kpi dashboard in R".


- Páginas de bases de datos:
  - Chile
    - [[https://datos.gob.cl/][datos.gob.cl/]]
  - Universidad de Michigan
    - [[https://www.icpsr.umich.edu/web/pages/ICPSR/index.html][icpsr.umich.edu/web/pages/ICPSR/index.html]]
  - Universidad de California
    - [[https://archive.ics.uci.edu/ml/datasets.php][archive.ics.uci.edu/ml/datasets.php]]
  - Kaggle
    - [[http://www.kaggle.com][kaggle.com]]


- Tipos de variable.
  - Son 4 en total.


- ¿Explicación para valores atípicos?
  - O es un error humano o es simplemente
    un valor extremo.
  - ¿Existe alguna variable que pueda explicar
    este valor atípico?
    - En caso de distribución de sueldos, la
      variable "experiencia" puede explicar
      valores atípicos. Tambien lo pueden hacer
      la variable "nivel de educación".

- Preguntas para hacerse respecto a valores atípicos:
  1) ¿Es posible este valor atípico? Independiente
     de si es extremo real o error humano.
  2) ¿Qué necesito para modificar este dato con el
     objetivo de tener resultados más consistentes?


- ¿Cuándo la información es correcta? Cuando
  los datos son correctos.


#+begin_example

         +-------------+
         |             |
   Datos |   Proceso   | Información
  ------>+             +--->
         |             |
         |             |
         +-------------+

#+end_example


Estratificación:

Para todos los datos que superen cierto =valor=,
se crea un nuevo grupo para evitar efecto de
valores atípicos.

#+begin_example R
datos$columna[datos$otra_columna>=valor] <- c(4)
#+end_example

** [2022-04-08 Fri] Clase
:CLOCKBOOK:
CLOCK: [2022-04-08 Fri 09:16]--[2022-04-08 Fri 10:36] =>  1:20
:END:

- Utilizamos archivo "PSU_diagnostico_01.xlsx".


- ¿En qué prueba les va mejor?
  - La que tiene una mediana superior a la media.


Usamos =descriptY=: cosas que podemos observar:
- Hay valores atípicos presentes.
  - El mínimo real es inferior a la bisagra inferior,
    y el máximo real es superior a la bisagra
    superior.


Asimetría positiva \(\rightarrow\) Cola
hacia la derecha \(\rightarrow\) De los
valores atípicos, los esperados son
los del lado derecho, los del lado izquierdos
son valores atípicos inesperados.


Dados que son datos de estudiantes de ingeniería,
¿En cuál prueba les debería ir mejor: matemática
o lenguaje? ¿Qué tanto más?

¿Qué indica la curtosis?
- Cúanto, no dónde, se concentran los datos.
  Mayor curtosis, mayor concentración. No
  considera /dónde/ se concentran.


En =rend1=, el resultado es expresado en
porcentaje de buenas.
- Las bisagras entregadas no tienen sentido,
  la mínima es negativa y la máxima es mayor
  a 100.
- Que tanta informacion relevante aporta
  un porcentaje de =0=? Que tan probable
  es que un estudiante de ing tenga /todas/
  malas en una prueba de matematica?
  - Que no haya asistido, o que responda
    todas malas a conciencia no es relevante.
    Si responde a conciencia, y aun así
    tiene /todas/ malas, ahí si es relevante,
    pero ese caso es muy improbable.


Por todas estas razones, se eliminan los
puntajes 0 de la data original, pues no aportan
información relevante a las conclusiones.

: data <- dataOriginal

Copiamos los datos a una nueva base de datos
para no alterar el original.

luego
: data$rendida <-c(0)

No se elimina nada, sino que la variable ahora
describe cuando rinden o no rinden el examen.

Ahora:
: data$rendida[data$rend1>0]<-c(1)

Cuando /sí/ rinden el examen, la variable
=rendida= es =1=. Cuando no, es =0=.

Sin embargo, se debe mencionar en el informe
final que hubieron ciertos elementos no
considerados.


Eliminando los =0=, las bisagras siguen iguales,
pero los mínimos y máximos reales se ajustan.

Sin embargo, la curtosis disminuye, siendo
que debería aumentar; la curtosis mide la
concentración de datos. Mayor curtosis,
mayor concentración.

** [2022-04-12 Tue]

- Semana 2-5: ejemplo prueba pasada.

*** Ejemplo

Dada una base de datos:
1) Enuncie una pregunta de investigación
   respecto de las variables que aparecen en
   el data set, para la hoja PROB1 y otro
   para la PROB2.(2p)
2) Respecto de los datos de PROB 1, ¿Qué
   variable pudiese afectar en la variabilidad
   del tamaño muestral?. Si lo desea, puede
   hacer ajustes a su contexto. (2p)
3) Respecto de los datos de PROB 2, que tipo
   de Muestreo podría usar, explique cómo lo
   usaría. (3p)
4) Evalúe la calidad de los datos. Prob 1 y
   Prob 2.
   1) Si existen valores atípicos, explique en
      cuál es la mejor opción para tratar estos
      valores. si no existiesen, explique qué
      valores pudiesen ser considerados V.A.
      especulando. (4p), arregle el data set
      de ser necesario.
5) Evalúe la variable, por si sola. en la
   hoja Prob 1 (4p).
6) Evalúe la variable respecto de un factor
   de la variable independiente. en la hoja
   Prob 2 (4p).

*** Conceptos

- Tipos de muestreo.
- ¿Cómo sé si los datos están correctos,
  estadísticamente hablando?
  - Que los datos atípicos sean esperables.
  - Simetría positiva, datos atípicos hacia
    la derecha.
  - Simetría negativa, datos atípicos hacia
    la izquierda.


Si tengo datos atípicos, o son un error,
o simplemente son reales.


Tratamientos para los valores atípicos.
- Eliminar:
  - Cuando es un error.
- Modificar:
  - Cuando puedo identificar la fuente del valor.
    Hacer trazabilidad.
- Tomarlo en cuenta:
  - Detectando que es un valor que ocurre, está
    cerca de la bisagra.


Acerca del error:
- Datos -> Proceso -> Información.
  - Para info correcta, datos y proceso correctos.
- Datos buenos y proceso malo?

** [2022-04-26 Tue] Primera clase después de la 1 prueba

"Probabilidad: es la medida de verosimilitud
de ocurrencia de un EVENTO cuando se realice
el EXPERIMENTO (ξ).

Según Laplace está medida de ocurrencia
se obtiene como la relación entre los
CASOS FAVORABLES a la ocurrencia del
EVENTO o SUCESO y todos posibles casos
que puedan ocurrir o los casos pertenecientes
al ESPACIO MUESTRAL (Ω)."

- Conceptos basicos:
  - Experimento
    - situación realizable o proceso acontecido,
      el cual debe ser evaluado de manera numérica.
  - Probabilidad
    - medida de ocurrencia.
  - Suceso
    - resultado mínimo en el resultado
      de un experimento.
  - Evento
    - conjunto específico de sucesos simples.
  - Espacio Muestral
    - conjunto de todos los posibles resultados
      del experimento.


*Pregunta de prueba*: ¿Cuáles deben ser las
condiciones para que los resultados tengan sentido?
- "¿Cuál es el experimento?"
- "¿Cuáles son las condiciones del experimento?"


Teoremas:
#+begin_src latex
\begin{align*}
  P(\varnothing)=\frac{\#\varnothing}{\#\Omega}=0 \\
  P(\Omega)=\frac{\#\Omega}{\#\Omega}=1 \\
  0 \leq P(A) \leq 1 \\
  \sum_{i=1}^{n}P(A_{i})=1\\
\end{align*}
#+end_src


Combinaciones y Permutaciones.

*Eventos dependientes*.

#+begin_src latex
\begin{venndiagram2sets}[labelOnlyA{A},labelonlyB{B},labelNotAB{aoeu}]
  \fillACapB
\end{venndiagram2sets}
#+end_src

*Probabilidad intersección de eventos*.

* Ayudantías :assistantship:
** inactive-time-stamp clase x
# - Then =org-clone-subtree-with-time-shift= and repeat
- log link by ID
- =org-timer-start=


< your_notes >

** [2022-04-13 Wed] Ayudantía 1
*** Parte1: R

- Ayudante: j.mainhard01@ufromail.com
  - discord: koke#5991

- dinfo.ufro.cl/eduroam


- https://rstudio.cloud/


- https://aur.archlinux.org/packages/rstudio-desktop


- https://stackoverflow.com/questions/2127246/difference-between-affero-gpl-and-gplv3
- https://www.gnu.org/licenses/why-affero-gpl.html
- https://www.networkworld.com/article/2229265/is-the-affero-gpl-unfriendly-to-hobbyists-.html

*** Parte2: Proba

- 2 tipos de variables: dependiente e independiente.
  - Dependiente: aquella en cual basamos nuestra
    respuesta.
  - Independiente: explica la variación de
    la independiente.
- Mención a población vs muestra
- Curtosis
  - Leptocurtosis
    - 1<<curtosis
  - Mesocurtosis
    - 0<curtosis<1
  - Platocurtosis
    - curtosis<0


- Asimetría
  - Positiva: cola hacia la derecha
    - mo<me<pr
  - Negativa: cola hacia la izquierda
    - pr<me<mo
  - -0.08<asimetría<0.08
    - Se considera simétrica.

* Resúmenes para evaluaciones
- link-to-resumen-eval1.org
- link-to-resumen-eval2.org
- link-to-resumen-eval3.org
* Local variables :noexport:
# Local Variables:
# ispell-local-dictionary: "espanol"
# End:

#  LocalWords:  curtosis
