#+INCLUDE: "~/org/uni/org/config.org"
#+FILETAGS: :university:
#+TITLE: Gestión de Recursos Humanos
#+SUBTITLE: RRHH

* TOC :TOC_2:noexport:
- [[#clases][Clases]]
  - [[#about][About]]
  - [[#2022-03-22-tue-clase-1][[2022-03-22 Tue] Clase 1]]
  - [[#2022-03-29-tue-clase-2][[2022-03-29 Tue] Clase 2]]
- [[#ayudantías][Ayudantías]]
  - [[#inactive-time-stamp-clase-x][inactive-time-stamp clase x]]
- [[#resúmenes-para-evaluaciones][Resúmenes para evaluaciones]]

* Clases :lecture:
** About
- Copia el contenido de "Clases" en "asignatura.org"
- Pegalo en esta sección
- Elimina el dia, dejando las clases únicamente
- Selecciona visualmente las clases
  + Tambien puedes seleccionar el contenido del heading "Clases", es lo mismo.
    - Se hace con =v i R=: "visual inside R"
      + La R hace referencia al contenido interior de un heading
- =org-sort= alpha


- Asi deberias tener luego las clases ordenadas por numero de clase
- Mientras que en "asignatura.org" estaran ordenadas por el dia
** [2022-03-22 Tue] Clase 1
:PROPERTIES:
:ID:       699d1615-9a1d-4154-b29e-46c9f6a84067
:END:
- [2022-03-22 Tue 17:07]
- Clase del martes pasado fue solo introductoria.


*** Materia

Contexto-conceptos y gestión de RRHH.
-----
Complejidades para análisis en RRHH.

-----
*Sistema*

Ejemplo empresa de venta de papas fritas;
verlo como un /sistema/ /abierto/
(input,output):

- ¿Qué elementos necesitamos para ofrecer el
  producto/servicio?

------
*Entorno*
- Ejemplo supermercado; Unimarc:
  - Recursos TC-
  - RRHH.
  - RR Intangibles.
    - Patentes alcoholes, casinos.
  - Competencia (Macro-entorno).


Intangible: compra-venta cafetería funcionando.

-----
*Ambiente de trabajo (micro y macro)*
-----
*Socios*
- Stakeholders
  - Todos a quien le interesa que a la
    empresa de papas fritas le vaya bien.
    - El agricultor.
    - Proveedor.
      - Nos proveen cosas.
    - Acreedores.
      - Nos proveen dinero.
-----
*Necesidades*
-----
*Conducta*
- Ejemplo terremoto.
  - Las personas reaccionan de forma diferente.
-----
*Motivaciones*
- o Estimulos.
-----

** [2022-03-29 Tue] Clase 2
:CLOCKBOOK:
CLOCK: [2022-03-29 Tue 17:13]
:END:

- Contexto - Conceptos y Gestión de RRHH.
  - Repaso clase anterior.


- Entorno de la organización.
  - Perfil organizacional.
  - Micro-entorno.
  - Macro-entorno.


- 2200 personas aprox trabajan en la UFRO,
  dependiendo del contrato.
  - Incluye sedes fuera de Temuco.
  - 600 a honorario.
  - Algunas gratis.
  - *Micro-entorno*: otras universidades.
  - *Macro-entorno*: otras industrias.
    - Electricidad
    - Retail
    - Bancos
    - etc
  - ¿Por qué a las mineras no les afecta mucho el
    aumento en el sueldo mínimo?
  - Efecto del aumento de combustible.
  - Efecto del aumento del dolar.
    - Importar vs exportar.


- Ambiente general: Factores económicos
  - Ambiente de trabajo: Otras organizaciones.
    - Organización.


- Ambiente general:
  - Sociales.
  - Legales.
  - Políticos.
  - Demográficos.
  - Culturales.
  - Tecnológicos.
  - Factores económicos.
- Ambiente de trabajo
  - Competidores.
  - Clientes.
  - Entidades reguladoras.
  - Proveedores.
  - Otras organizaciones.


- Factores de macroentorno.
  - P: Políticos.
  - E: Económicos.
  - S: Sociales.
  - T: Tecnológicos.
  - A: Ambientales.
  - C: culturales.


- Camino de las organizaciones:
  *Definición de Términos*.
- Se consigue y cambian.
  1) Estrategia:
     - Cómo alcanzo la visión de la organización.
     - Acciones y tareas:
       - Metas y objetivos.
  2) Visión:
     - Visión: en que me quiero convertir.
       - Normalmente de largo plazo.
       - Nuestro caso: "ser ing civi ind, y quiero
         trabajar en <X>."

-----
- No cambia y no se completa.
  3) [@3] Valores:
     - Inspiracion para la ejecución.
  4) Misión
     - Misión: "¿Para qué se existe?"; la razón
       de ser de la organización.
       - En el largo plazo, las misiones no se ven
         alteradas, cambian las estrategias y las
         formas, pero la misión no.


*Enfoques estructurales*
- Enfoque funcional:
  - Foco:
    - Procesos.
    - Resultados.
    - Trabajo conjunto.
    - Equipos autónomos y multidisciplinarios.
    - Cooperación /inter/-departamental.
    - Más integrado con el entorno.
- Enfoque sistémico:
  - Foco:
    - Especialización.
    - Cooperación /intra/-departamental.
    - Más aislado.


*Modelos*
- Centralizados:
  - Monopolio de RRHH.
  - Tratamiento genérico para todos.
- Descentralizados:
  - Actividades delegadas.
  - Tratamiento personalizado.


*Rol de RRHH*
- Dave Urlich


#+begin_src example
 (Actividad) Estratégicas
                  |
 "Lider           |
  Estrategico"    | "Gestor del Cambio"
                  |
            [4]   |  [3]
                  |
Procesos -------------------- Personas
                  |
 "Experto         | "Defensor de los
  Administrativo" |  trabajadores"
                  |
            [1]   |  [2]
                  |
 (Actividad) Operativas
#+end_src

1) Decisiones: "Experto Administrativo".
   - Roles más conocidos del área de RRHH.
   - Pagos.
   - Controles.
     - Verificación de horario.
     - Horas trabajadas.
   - Contratos.
   - Procesos y funciones.
   - Bonos.
   - Aguinaldos.
   - Comisión.
   - Verificación de cumplimiento de metas.
   - Declaración de impuestos.
   - "Cómo puede ofrecer RRHH una base de
     servicios para que la organización
     sea eficiente y eficaz".
   - Administración de la infraestructura
     de la empresa.
2) Personas: "Defensor de los trabajadores".
   - "Adalid".
   - Reconocimientos.
   - Celebraciones.
   - Vestuario y elementos de seguridad.
   - Administración de vacaciones.
   - Actividades.
   - Becas.
   - "Cómo puede ayudar RRHH en el involucramiento
     y compromiso de los empleados."
   - Administración de la contribución de los
     empleados.
3) "Gestor del Cambio".
   - Perfiles de cargo.
     - ¿Qué se necesita para postular a este cargo?
   - Reclutamiento y selección.
   - "Cómo puede ayudar RRHH en la construcción
     de una organización creativa, renovadora e
     innovadora."
   - Administración de la transformación y el
     cambio.
4) "Lider Estratégico"
   - ¿Qué aprendizaje le dejó, a la organización,
     el estallido social?
   - "Cómo puede ayudar RRHH a impulsar la
     estrategia organizacional."
   - Administración de las estrategias de RRHH.
-----
* Ayudantías :assistantship:
** inactive-time-stamp clase x
# - Then =org-clone-subtree-with-time-shift= and repeat
- log link by ID
- =org-timer-start=


< your_notes >

* Resúmenes para evaluaciones
- link-to-resumen-eval1.org
- link-to-resumen-eval2.org
- link-to-resumen-eval3.org
* Local variables :noexport:
# Local Variables:
# ispell-local-dictionary: "espanol"
# End:

#  LocalWords:  RRHH
