#+INCLUDE: "~/org/uni/org/config.org"
#+FILETAGS: :university:
#+TITLE: Gestión de Recursos Humanos
#+SUBTITLE: Apuntes de la clase
#+option: toc:2

* TOC :TOC_2:noexport:
- [[#clases][Clases]]
  - [[#about][About]]
  - [[#2022-03-22-tue-clase-1][[2022-03-22 Tue] Clase 1]]
  - [[#2022-03-29-tue-clase-2][[2022-03-29 Tue] Clase 2]]
  - [[#2022-03-31-thu-clase-3][[2022-03-31 Thu] Clase 3]]
  - [[#2022-04-05-tue-clase-4][[2022-04-05 Tue] Clase 4]]
  - [[#2022-04-12-tue-clase-5][[2022-04-12 Tue] Clase 5]]
  - [[#2022-04-14-thu-clase-6][[2022-04-14 Thu] Clase 6]]
  - [[#2022-04-21-thu-clase][[2022-04-21 Thu] Clase]]
  - [[#2022-04-26-tue-clase-resumen-para-primera-prueba][[2022-04-26 Tue] Clase resumen para primera prueba]]
- [[#footnotes][Footnotes]]

* Clases :lecture:
** About
- Copia el contenido de "Clases" en "asignatura.org"
- Pegalo en esta sección
- Elimina el dia, dejando las clases únicamente
- Selecciona visualmente las clases
  + Tambien puedes seleccionar el contenido del
    heading "Clases", es lo mismo.
    - Se hace con =v i R=: "visual inside R"
      + La R hace referencia al contenido interior de un heading
- =org-sort= alpha


- Asi deberias tener luego las clases ordenadas por numero de clase
- Mientras que en "asignatura.org" estaran ordenadas por el dia
** [2022-03-22 Tue] Clase 1
:PROPERTIES:
:ID:       699d1615-9a1d-4154-b29e-46c9f6a84067
:END:
- [2022-03-22 Tue 17:07]
- Clase del martes pasado fue solo introductoria.


Contexto-conceptos y gestión de RRHH.
-----
Complejidades para análisis en RRHH.

-----
*Sistema abierto*

Ejemplo empresa de venta de papas fritas;
verlo como un /sistema/ /abierto/
(input,output):

- ¿Qué elementos necesitamos para ofrecer el
  producto/servicio?

------
*Entorno*
- Ejemplo supermercado; Unimarc:
  - Recursos TC-
  - RRHH.
  - RR Intangibles.
    - Patentes alcoholes, casinos.
  - Competencia (Macro-entorno).


Intangible: compra-venta cafetería funcionando.

-----
*Ambiente de trabajo (micro y macro)*
-----
*Socios*
- Stakeholders
  - Todos a quien le interesa que a la
    empresa de papas fritas le vaya bien.
    - El agricultor.
    - Proveedor.
      - Nos proveen cosas.
    - Acreedores.
      - Nos proveen dinero.
-----
*Necesidades*
-----
*Conducta*
- Ejemplo terremoto.
  - Las personas reaccionan de forma diferente.
-----
*Motivaciones*
- o Estimulos.
-----
** [2022-03-29 Tue] Clase 2
:CLOCKBOOK:
CLOCK: [2022-03-29 Tue 17:13]--[2022-03-29 Tue 19:00] =>  1:47
:END:

- Contexto - Conceptos y Gestión de RRHH.
  - Repaso clase anterior.


- Entorno de la organización.
  - Perfil organizacional.
  - Micro-entorno.
  - Macro-entorno.


- 2200 personas aprox trabajan en la UFRO,
  dependiendo del contrato.
  - Incluye sedes fuera de Temuco.
  - 600 a honorario.
  - Algunas gratis.
  - *Micro-entorno*: otras universidades.
  - *Macro-entorno*: otras industrias.
    - Electricidad
    - Retail
    - Bancos
    - etc
  - ¿Por qué a las mineras no les afecta mucho el
    aumento en el sueldo mínimo?
  - Efecto del aumento de combustible.
  - Efecto del aumento del dolar.
    - Importar vs exportar.


- Ambiente general: Factores económicos
  - Ambiente de trabajo: Otras organizaciones.
    - Organización.


- Ambiente general:
  - Sociales.
  - Legales.
  - Políticos.
  - Demográficos.
  - Culturales.
  - Tecnológicos.
  - Factores económicos.
- Ambiente de trabajo
  - Competidores.
  - Clientes.
  - Entidades reguladoras.
  - Proveedores.
  - Otras organizaciones.


- Factores de macroentorno.
  - P: Políticos.
  - E: Económicos.
  - S: Sociales.
  - T: Tecnológicos.
  - A: Ambientales.
  - C: culturales.


- Camino de las organizaciones:
  *Definición de Términos*.
- Se consigue y cambian.
  1) Estrategia:
     - Cómo alcanzo la visión de la organización.
     - Acciones y tareas:
       - Metas y objetivos.
  2) Visión:
     - Visión: en que me quiero convertir.
       - Normalmente de largo plazo.
       - Nuestro caso: "ser ing civi ind, y quiero
         trabajar en <X>."

-----
- No cambia y no se completa.
  3) [@3] Valores:
     - Inspiracion para la ejecución.
  4) Misión
     - Misión: "¿Para qué se existe?"; la razón
       de ser de la organización.
       - En el largo plazo, las misiones no se ven
         alteradas, cambian las estrategias y las
         formas, pero la misión no.


*Enfoques estructurales*
- Enfoque funcional:
  - Foco:
    - Procesos.
    - Resultados.
    - Trabajo conjunto.
    - Equipos autónomos y multidisciplinarios.
    - Cooperación /inter/-departamental.
    - Más integrado con el entorno.
- Enfoque sistémico:
  - Foco:
    - Especialización.
    - Cooperación /intra/-departamental.
    - Más aislado.


*Modelos*
- Centralizados:
  - Monopolio de RRHH.
  - Tratamiento genérico para todos.
- Descentralizados:
  - Actividades delegadas.
  - Tratamiento personalizado.


*Rol de RRHH*
- Dave Urlich


#+begin_src example
 (Actividad) Estratégicas
                  |
 "Lider           |
  Estrategico"    | "Gestor del Cambio"
                  |
            [4]   |  [3]
                  |
Procesos -------------------- Personas
                  |
 "Experto         | "Defensor de los
  Administrativo" |  trabajadores"
                  |
            [1]   |  [2]
                  |
 (Actividad) Operativas
#+end_src

1) Decisiones: "Experto Administrativo".
   - Roles más conocidos del área de RRHH.
   - Pagos.
   - Controles.
     - Verificación de horario.
     - Horas trabajadas.
   - Contratos.
   - Procesos y funciones.
   - Bonos.
   - Aguinaldos.
   - Comisión.
   - Verificación de cumplimiento de metas.
   - Declaración de impuestos.
   - "Cómo puede ofrecer RRHH una base de
     servicios para que la organización
     sea eficiente y eficaz".
   - Administración de la infraestructura
     de la empresa.
2) Personas: "Defensor de los trabajadores".
   - "Adalid".
   - Reconocimientos.
   - Celebraciones.
   - Vestuario y elementos de seguridad.
   - Administración de vacaciones.
   - Actividades.
   - Becas.
   - "Cómo puede ayudar RRHH en el involucramiento
     y compromiso de los empleados."
   - Administración de la contribución de los
     empleados.
3) "Gestor del Cambio".
   - Perfiles de cargo.
     - ¿Qué se necesita para postular a este cargo?
   - Reclutamiento y selección.
   - "Cómo puede ayudar RRHH en la construcción
     de una organización creativa, renovadora e
     innovadora."
   - Administración de la transformación y el
     cambio.
4) "Lider Estratégico"
   - ¿Qué aprendizaje le dejó, a la organización,
     el estallido social?
   - "Cómo puede ayudar RRHH a impulsar la
     estrategia organizacional."
   - Administración de las estrategias de RRHH.
-----
** [2022-03-31 Thu] Clase 3
:CLOCKBOOK:
CLOCK: [2022-03-31 Thu 08:46]--[2022-03-31 Thu 09:58] =>  1:12
:END:

Rol y KPI en la Gestión de RRHH.

-----
Subsistemas de RRHH
- Integración
  - Reclutamiento, selección, inducción,
    contratación y desvinculación.
- Organización
  - Diseño, descripción de puestos,
    evaluación de desempeño.
- Retención
  - Pago de sueldos, imposiciones,
    licencias médicas, cargas familiares,
    seguros, políticas de reconocimientos,
    beneficios, clima laboral, calidad de vida.
- Desarrollo
  - Formación, planes de carrera y sucesión.
- Auditoría
  - Bases de datos, sistemas, ética y
    responsabilidad.
-----
** [2022-04-05 Tue] Clase 4
:CLOCKBOOK:
CLOCK: [2022-04-05 Tue 17:15]--[2022-04-05 Tue 18:36] =>  1:21
:END:

Rol y KPI en la Gestión de RRHH.

*Concepto de imposiciones*: descuentos que se
hacen en forma de redirección de las remuneraciones
de los trabajadores en beneficio de los mismos.
- Seguros de cesantía.
- Cajas de compensación.
- Isapres.
- Seguros médicos.
  - Patologías temporales y permanentes.
- Cargas familiares.


Tipos de autoridad de RRHH: Línea vs Staff.
- Organigrama


"La planificación estratégica de RRHH debe
vincular el quehacer de RRHH con la
planificación Estratégica de la organización."

Pirámide organizacional:
- Niveles más altos:
  - Menos gente, decisiones mas estratégicas.
- Niveles más bajos:
  - Más gente, decisiones más operativas.


¿Cómo relacionar la estrategia y la gestion?

Control.
- de mercado.
- burocrático.
- de clan.

¿Por qué es importante el control?
- Es el vínculo final en las funciones
  de la gerencia.
- Es la forma de saber si los objetivos se
  están cumpliendo o no.
- Permiten desarrollar seguimiento.
- Ayuda a tomar decisiones de futuro.
- "Empowerment": "Empoderamiento".


"La razón final del control es la protección
de la organización y del centro de *trabajo*".


"El proceso de control":
1. Medición del desempeño real.
2. Comparación con estándar.
3. Toma de medidas para corregir desviaciones.


Ejemplo choripanada FICA.


Oportunidad para controlar el desempeño en
una organización.
- Alimentacion anticipada.
- Concurrente.
- Retroalimentacion.


Herramientas para el control:
- Financieros
- Cuadros de mando
- Información
- Benchmarking


"Los controles deben ser suficientes,
fáciles de comprender, relevantes y pertinentes
para medir directamente el logro de los objetivos".

Estos controles son los renombrados *KPI*.

"Los KPI son el medio para verificar el
cumplimiento de los objetivos estratégicos."

Los KPI deben ser S.M.A.R.T[fn:1].


Cuadro de Mando Integral o
BSC (/Balance/ /Score/ /Card/)

- Una parte gráfica de lluvia de ideas.
- Otro parte, el tablero de comandos.


Ejemplo de BSC de Canal 13.


Próxima clase: formación de KPIs.

-----
** [2022-04-12 Tue] Clase 5

Empezamos con nueva unidad.

Unidad 3: Provisión/Integración de RRHH.


- Procesos de selección.
  - No es lo mismo que elegir unos lentes
    que elegir personal.
- Análisis y descripción de puestos.
- Problema de falta de objetivos.
  - Duplicación de esfuerzo o funciones.
- Solución: puestos o cargos.
  - Conjunto de funciones predefinidas
    en una estructura organizacional.
- Perfil = cargo + extras.
  - extras: habilidades blandas, información
    específica del puesto, etc.
- Evolución de los perfiles.
  - por distintos motivos, avances tecnológicos,
    cambios en paradigmas sociales, etc.


Nasa: 18,300 postulantes en 2021[fn:2]. 200,000
mencionados en la clase.


Etapas de selección:
1) Relevamiento de la información. Análisis del
   puesto de trabajo:
   - ¿Qué información recopilamos?
   - ¿Cómo recopilamos la información?
2) Confirmación de la información. 
3) Descripción del puesto[fn:3].
   - Generación del documento.

   
\begin{tcolorbox}
  \begin{center}
    La profesora nombra el triángulo de
    las competencias. Básicamente:
    - Manejar teoría.
    - Manejar práctica.
    - Sentido común.
    
    
    Existen diferentes modelos para perfiles
    que carecen de 0,1,2 o 3 de las 3 aristas
    del triángulo.
  \end{center}
\end{tcolorbox}
   
** [2022-04-14 Thu] Clase 6

Repaso clase anterior.

-----

- Gestión de RRHH por competencias.
- Triángulo de las competencias.
  - Saber
  - Hacer
  - Ser


- Caso UFRO: 11 competencias[fn:4].
  1) Aprender a aprender.
  2) Compresión lectora.
  3) Comunicación escrita.
  4) Comunicación en ingles.
  5) Comunicación verbal.
  6) Emprendimiento.
  7) Liderazgo.
  8) Pensamiento critico.
  9) Responsabilidad social.
  10) Trabajo en equipo.
  11) Uso de TIC.
- Identificación y fortalecimiento de
  competencias.
  - Promedio: 6 meses en crear una competencia.
- Siguiente: predicción de comportamiento.
  - El saber competencias pasadas, permite
    predecir competencias futuras[fn:5].


Tipos de competencias:
- Cardinales, estratégicas, o genéricas:
  - Presentes transversalmente en la organización.
  - Ej: innovación.
- Específicas: 
  - Ej: programación en Java.


- Identificación profesional online: Linkedin.

- Reclutamiento vs selección.
  1. Reclutar: Buscar postulantes al por mayor.
  2. Selección: Seleccionar a mano.


- Error común: acomodar el puesto al postulante
  dada una muy buena impresión del postulante,
  siendo que hay otros que se acomodan más al
  perfil buscado. Lo debe ocurrir es que el
  postulante se debe acomodar a las necesidades
  del cargo.

** [2022-04-21 Thu] Clase

1) Competencias
2) Reclutamiento
3) Selección

-----

1) Requerimiento: Necesidad de empresa.
2) Definición del cargo:
   1) Recopilación de información.
   2) Validación.
   3) Formación de perfil.
3) Publicación y difusión de perfil.
4) Recepción de postulaciones:
   - Reclutamiento y selección.
   - Head hunter.
   - Hunting.
5) Revisión curricular
   1) Proceso de adecuación inicial
   2) Revisión perfil
   3) Orden x puntaje
   4) Ranking
6) Entrevistas
   - También le ponen puntaje.
   - Básicamente todo tiene puntaje.
   - Preguntas de todo tipo.
   - Evaluaciones psicológicas implícitas.
   - Evaluación psico-laboral.
     - Tambien con puntaje[fn:6].
7) Selección de candidatos finales.
   1) Revisión caso a caso.
   2) Entrevistas finales.


-----
Procesos de decisión de postulantes y puestos:
- De colocación:
  - Un postulante, un puesto.
- De selección:
  - Varios postulantes, un puesto:
    - Se comparan.
- De clasificación:
  - Varios postulantes, varios puestos.
    - Se comparan y se asignan distintos
      postulantes a distintos posibles puestos,
      dependiendo de las demandas del cargo
      y las ofertas de cada postulante.

** [2022-04-26 Tue] Clase resumen para primera prueba

¿Por qué el analisis de RRHH es complejo?:
Por el micro y macro entorno en el que desenvuelven
las empresas.


- Sistema abierto: la org se relaciona
  con otras orgs.
- Socios: a quienes les interesa que a la
  empresa le vaya bien. Partes interesadas
  en la empresa.


Proveedores vs acreedores: los proveedores
te entregan bienes y servicios directamente
relacionados con el proceso productivo.
Los acreedores te entregan otras formas
para facilitar el proceso productivo.
Por ejemplo: el acreedor te entrega dinero,
y el proveedor te entrega materia prima.

Las personas tienen *necesidades* diversas.

- ¿Cómo reconocemos la misión de las organizaciones?
- ¿Cómo evaluamos la centralización o
  descentralización de los procesos?
- ¿Por qué es importante el control?
- ¿Etapas del proceso de selección?
- ¿Por qué elaborar bases de reclutamiento
  y selección?:
  - Las bases son la fundación del
    proceso de reclutamiento y selección.
- ¿Qué aspectos debemos considerar en una
  entrevista de selección?
  - Cosas que no se pueden preguntar en
    una entrevista:
    - por la vida privada en general.
    - por la orientación sexual.
    - por los hijos.
    - por su estado civil.
    - por la religión.
    - por los hobbies.
    - por política.
    - por enfermedades.
      - Los requisitos del trabajo están tipificados
        en las bases del puesto.
      - No se debe preguntar sobre ellos pues se
        supone que ya están considerados en otras
        secciones.
- Subsistemas de RRHH
  - Auditoría: ej: verificación del
    funcionamiento no solo correcto si no
    que también ético del software.
- Tipos de autoridad de RRHH: Línea vs Staff.
- ¿Cómo relacionamos la estrategia y la gestion?
  - Con los indicadores. KPI.
- ¿Qué tipos de control considera lo que
  están haciendo otras organizaciones
  en materia de personas?
  - Control de mercado. También los hay /burocrático/
    y de /clan/.
- ¿Qué actividades puedes mencionar en el
  modelo de Dave Ulrich para las labores
  de RRHH?
  - Gráfico de "Rol de Recursos Humanos".
- ¿En qué momento se efectúa el control?
  - Anticipado.
  - Recurrente.
  - Retroalimentado.
- ¿Para qué sirven los KPI?
- ¿Qué aspectos son orientados por un tablero
  de comando o un /Balance/ /Score/ /Card/?
- ¿Diferencia entre micro y macro entorno?
- ¿PEST-PESTAC?
- ¿SMART KPIs?
- ¿Qué datos compara el control?
  - Variación entre el desempeño real y esperado.
- ¿Cómo levantamos un perfil de cargo?
  1) Relevamiento de la información.
  2) Confirmación de la información.
  3) Descripción y publicación del puesto.
- ¿Cuál es la diferencia entre reclutamiento
  y selección?



Maestros de pabellones:
- R: Salamana
- D: Molina.

* Ayudantías :assistantship:noexport:
** inactive-time-stamp clase x
# - Then =org-clone-subtree-with-time-shift= and repeat
- log link by ID
- =org-timer-start=


< your_notes >

* Resúmenes para evaluaciones :noexport:
- link-to-resumen-eval1.org
- link-to-resumen-eval2.org
- link-to-resumen-eval3.org

* Local variables :noexport:

* Footnotes

[fn:1] Buscar "S.M.A.R.T. goals".

[fn:2] https://www.nasa.gov/press-release/record-number-of-americans-apply-to-beanastronaut-at-nasa

[fn:3]
Ejemplo en clase:
- https://adp.serviciocivil.cl/concursos-spl/opencms/convocatoria/ADP-7072

[fn:4]
http://competenciasgenericas.ufro.cl/index.php/diccionario-de-competencias-genericas/

[fn:5]
En entrevistas, no te preguntan directamente,
te hacen contar una historia, y de esa historia
los reclutadores van formando un modelo.

[fn:6]
Entre el puntaje de la revisión curricular,
entrevista y evaluación psico-laboral ya se tienen
puntajes suficientes.

# Local Variables:
# ispell-local-dictionary: "espanol"
# End:
#  LocalWords:  RRHH Head hunter Hunting Ranking puntaje
