#+TITLE: Probabilidad y Estadística
#+SUBTITLE: Regresión
#+INCLUDE: "~/org/config/author-mfuica01.org"
#+INCLUDE: "~/org/config/config-spanish.org"
#+INCLUDE: "~/org/config/config.org"

* Introducción
- [[https://latexdraw.com/linear-regression-in-latex-using-tikz/][Linear Regression in LaTeX using TikZ - TikZBlog]]
- [[https://tex.stackexchange.com/questions/119179/how-to-add-a-regression-line-to-randomly-generated-points-using-pgfplots-in-tikz][How to add a regression line to randomly generated points using pgfplots in Tikz? - TeX - LaTeX Stack Exchange]]
* Correlación (R)
** Coeficiente de correlación (aka R o r)
- Es el nivel de relación existente entre
  2 variables; se entiende como el porcentaje
  de datos que poseen una asociación
  directa o inversa.
- Interpretación:
  - "De cada 100 pares de datos, R*100 tienen el
    mismo comportamiento".

** Correlación y calidad del modelo
:PROPERTIES:
:ID:       77f78879-51fa-4196-bdf0-15d43876b0a1
:END:

Una correlación = |1| /no/ es existe.
- Siempre hay errores.


- R<|0.2-0.3| \iff no hay relación.
- |0.4|<R<|0.6| \iff relación baja.
- |0.6|<R<|0.8| \iff relación media.
- |0.8|<R<|1.0| \iff relación alta.


- Profe Carlos trabaja con R>|0.7|.

* Determinación (R^2)
** Coeficiente de determinación (R^{2})
- Porcentaje de variación de Y que es explicado
  por X.
** Coeficiente de determinación ajustado(R^{2}_{aj})
- Lo mismo que R^2, pero considera fallas
  ocasionadas por el tamaño de la muestra.
** R^2 vs R^2_aj
- \(R^{2}_{aj} \leq R^{2}\)
- Si no hay problemas por el tamaño de la muestra,
  son iguales.
- Si hay problemas, \(R^{2}_{aj}\) tiende a
  ser menor.
- Ante una diferencia, hay que usar el ajustado.
- hasta 4% de diferencia es aceptable, luego,
  se usa R2 ajustado.
* Construcción y calidad del modelo
- Un modelo bien construido procura cumplir la
  mayor cantidad de [[id:806ba6ae-fb8c-47cb-9635-8433a4b40d80][supuestos]]. Un mal modelo
  no cumple con muchos supuestos.
- Un modelo bueno tiene una alta [[id:77f78879-51fa-4196-bdf0-15d43876b0a1][correlación]].


A partir de esto se pueden tener 4 tipos de
modelos:
- Modelos buenos bien construidos.
- Modelos buenos mal construidos.
- Modelos malos bien construidos.
- Modelos malos mal construidos.

* Supuestos para la realización de un modelo RLM (RLS)
:PROPERTIES:
:ID:       806ba6ae-fb8c-47cb-9635-8433a4b40d80
:END:
- u es el error.


1. E(u) = \bar u = 0.
2. V(u) es mínima.
3. u \sim N(0,\sigma^{2}_{u})
4. Los u's son independientes.
5. No auto-correlación.
6. Homocedasticidad.
   - Cedasticidad=dispersión.
   - De los errores.
7. No multicolinealidad.
   - Si no es cero, entonces tengo variables
     que están en función de otras variables.

* Condición de cálculo
- n: tamaño de la muestra.
- k: número de parámetros.


- n > k

* Simulaciones
- phet
  - [[https://phet.colorado.edu/sims/html/curve-fitting/latest/curve-fitting_en.html][Curve Fitting]]
* Método de Mínimos Cuadrados Ordinarios(MMCO)
- Relación con varianza y el supuesto 2?
* Notas de la clase
** [2022-06-17 Fri]
*** Independencia de errores
- [2022-06-17 Fri 09:25]
- Contexto: supuesto 4: independencia de
  los errores.


- Aumenta el Ingreso \implies Aumenta el gasto.



- Si el procedimiento de muestreo se hizo
  correctamente, entonces no debería
  haber relación entre los errores,
  por lo que cualquier supuesto patrón
  existente seria una relación espurica.
- Cuando existen pocos datos, es fácil encontrar
  patrones, pero puede que no tengan sentido.
- Ante la presencia de mas datos, encontrar un
  patrón se hace mas difícil; encontrar un
  patrón en ese caso, es mas probable que
  tenga una explicación lógica.


- [2022-06-17 Fri 09:34]
  - Auto-Correlación:
    - La variable tiempo puede no estar explícita,
      pero si explícita.

*** Pasos para un modelo bien construido
1) Calidad del dato
2) Construcción del modelo
3) Análisis de supuestos
4) Evaluar el medole
   1) Evaluar R
      : pearson
      - todas continuas
      : spearman
      - una discreta u ordinal
        - (generalmente la independiente)
      : \Tau de Kendall
      - dos discretas u ordinales
      : V de Cramer
      - ordinales
      : \Chi -cuadrado
      - nominal
   2) Modelo
      : anova(mod1)
   3) Evaluar R^2_{ajustado}
5) Evaluar parámetros


- \beta_{i} = 0 \iff significa que se debe construir
  un nuevo modelo.

*** Cantidad de estrellas y significancia
- 1: \alpha < 0.001
- 2: \alpha < 0.01
- 3: \alpha < 0.05
- 0: \alpha < 1


- Mientras más estrellas, "más menor" que \alpha.


: Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

*** Qué tipo de variable?
- La escala de medida determina el tipo de variable.
  - "Rojo".
    - Puede ser un color, estado de animo, nota,
      o cualquier cosa.
    - La unidad de medida determina a que
      tipo de variable nos estamos refiriendo.
*** Anova
*** R^2
- ¿Qué porcentaje de X puede explicar la varianza de Y.
- O qué porcentaje de la varianza de Y puede
  ser explicado por X.
*** R^2_{aj}
- Si \(R^2\) > \(R^2_{aj}\)
  - Si no puedes aumentar el tamaño de la muestra,
    entonces trabaja con el ajustado.
*** Qué es el residual?
- \(u = Y - \cap Y\)

** [2022-06-22 Wed]
- Qué significa B0 igual a 0?
  - Que hay que hacer otro modelo ajustado.
- [2022-06-22 Wed 12:00]
  - "Si el S de la media de los errores no se cumple
    y el supuesto de normalidad tampoco,
    entonces olvídate del modelo".
- [2022-06-22 Wed 12:10]
  - "De los modelos presentes, el menos malo es..."
- [2022-06-22 Wed 12:25]
  - Ejemplo 11.3 del libro en campus.
- [2022-06-22 Wed 12:33]
  - "Para un modelo simple, el Beta 1 tiene que
    tener el mismo signo que el R."
** [2022-07-01 Fri]
- Lunes, RA1002.

* Scripts usados
** para la materia
- SCRIPT_A01_4_descripY.R
- SCRIPT P01 Analisis de Distribucion.r
- SCRIPT P02 Analisis de Distribucion.r
- SCRIPT REGRESION MULTIPLE.r

** ejemplos en clases
*** [2022-06-14 Tue]
- datos<-PSU_diagnostico_01

#+begin_example R
source ("~/Downloads/uni/2022-1/proba/scripts-r/SCRIPT_A01_4_descripY.R")
source ("~/Downloads/uni/2022-1/proba/scripts-r/SCRIPT REGRESION MULTIPLE.r")

# eliminamos los que no rindieron la prueba
datos<-datos[datos$rend1>0,]

# Analisis supuesto colinealidad
chart.Correlation(datos)
# se recomienda identificar la variable sensible: "la que
# no tengo que tocar"

# elimino las variables colineales
datos<-dplyr::select(PSU_diagnostico_01,-PEM,-HIST,-PROMPSU,-PSUPOND,-LENG,-CS)
# tienen que estar en el mismo orden

model01<-lm(datos$rend1~.,data=datos)
vif(model01) # el output: ojala 1, o lo mas cercano a 1
summary(model01)

# Analisis supuestos
# S1
# mean(model01$residuals)

# S2
# Metodo de minimos cuadrados

# S3 errores se comportan normal
# HO: los datos se comportan normal
# shapiro.test(model01$residuals)
# andersen
# cramer
# lilly
# pearson
# ks
# todos lo de la libreria nortest

# S4 errores independientes
# plot(model01$residuals)

# S5 no autocorrelacion
# HO: no existe autocorrelacion
# Test DurbinWatson
# dwtest(model01)

# S6 Homocedasticidad
# HO: varianzas iguales
# test BreuschPagan
# bptest(model01)

# S7 No multicolinealidad
# HO: no hay variables colineales
#+end_example

*** [2022-06-17 Fri]
*** [2022-06-28 Tue]
- Datos:
: "~/Downloads/uni/2022-1/proba/data/2/reg-2 variables ind.xlsx
- Script de referencia:
: ~/Downloads/uni/2022-1/proba/scripts-r/20220628/SCRIPT REG LINEAL SIMPLE v01-05.r

*** [2022-07-01 Fri]

#+begin_example R
# Incendios forestales
# Pasos para un modelo bien construido
# 1) Calidad del dato

# # IncendiosForestales importado desde excel
datos <- IncendiosForestales
y <- datos$Ind_Combustibilidad
x <- datos$temp
# # primera visualizacion en busca de datos atipicos
descripY(datos,y)

# 2) Construcion un modelo
mod1 <- lm(y~x,datos)

# - grafico4 (Residuals vs Leverage)
# en el word pego estos dos
plot(x,y)
plot(mod1) # el (Residuals vs Leverage)

# 3) Supuestos
# # 1) Promedio de los errores = 0
mean(mod1$residuals)
# # 2) Varianza de los errores minima
# # 3) Los errores se comportan normalmente
shapiro.test(mod1$residuals)
# todos los test de la libreria 'nortest'

# # 4) Independencia de los errores
plot(mod1$fitted.values,mod1$residuals)
# o el grafico 1 del
# plot(mod1) # recuerda apretar ENTER en la consola
# Si hay un patron en el grafico, entonces
# menos independientes son los errores
# Mientras menos datos, mas probable encontran un patron
# que no tiene verdadero sentido

# # 5) Autocorrelacion=0
dwtest(mod1)
# como en supuesto 3, para este caso libreria 'AER'

# # 6) Homocesdasticidad
# H0: homocedastico
# H1: heterocedastico
bptest(mod1)
# Requiere de un B0, por lo que si eliminamos el B0
# podemos ocupar el grafico 3 del plot(mod1)
# 'Scale-Location'
# Cuando el grafico se abre, es probable la
# heterocedasticidad
# Si se mantiene en una manga, entonces
# es homocedastico, independiente de la
# forma de la mango.
# Idealmente una manga con diametro constante.
# Aunque no se abra, si el diametro aumenta
# en algun momento, es probable la heterocedasticidad

# 4) Evaluar modelo
# # R:
cor.test(y,x,method="pearson")
# # Modelo
anova(mod1)
# Pr(F)=p-value                  : H0: modelo no existe
# meansq(residuals)=sigma2_err   : H1 : modelo existe
# Reporte
summary(mod1)
# intercept es la columna del B0
# x es la columna del B1
# Pr(t) es el p-value de cada uno donde el H0 es B_i = 0
# con i=(0,1)
# Si B0=0 entonces se propone un modelo nuevo
# Si B1=0 entonces la variable independiente no
# explica el comportamiento de la dependiente.
#+end_example

* Consulta al profe
- Suponiendo que el tamaño de la muestra tiene un
  impacto en el modelo, ¿Cuántas muestras más serían
  necesarias para obtener un modelo bueno?
  - Ejemplo, en las mineras, pocas muestras generan
    problema, se necesita calcular cuánto se debe
    invertir en más muestras y comparar si vale la
    pena.
* Libros
- En campus hay 2 muy buenos.
- Unidad 11: Regresión lineal simple y correlación.
  - pag 389.
* Local variables :noexport:
# Local Variables:
# ispell-local-dictionary: "espanol"
# End:

#  LocalWords:  curtosis Cedasticidad
